// Get all books
GET http://localhost:5000/api/books?page=0&result=5

###

// Get book by id
GET http://localhost:5000/api/books/4

###

// Create book (Success)
POST http://localhost:5000/api/books HTTP/1.1
content-type: application/json

{
  "title": "Test book 1",
  "genre": "Drama",
  "shelf": "Shelf #6",
  "description": "New test book",
  "image": null
}

###

// Create book (With errors)
PATCH http://localhost:5000/api/books/2 HTTP/1.1
content-type: application/json

{
  "title": "Harry Potter"
}

###

// Update book
PUT http://localhost:5000/api/books HTTP/1.1
content-type: application/json

{
  "title": "Update book",
  "genre_id": 2,
  "shelf_id": 3,
  "description": "Updated test book",
  "image": null,
  "id": 29
}

###

// Delete book
DELETE  http://localhost:5000/api/books/30 HTTP/1.1
